title: Runze Ni
description: Renal physiology, photography, cocktail notes, and working studies by Runze Ni.
url: "https://runzeni.github.io"
baseurl: ""
repository: runzeni/runzeni.github.io
lang: en-US

include:
  - .well-known

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - _site
  - .sass-cache
  - scripts
  - assets/R
  - assets/img/2022
  - assets/img/2023
  - assets/img/2024
  - assets/img/portfolio

collections:
  photobook:
    output: true
    permalink: /fotos/archive/:slug/
  notes:
    output: true
    permalink: /notes/:slug/
  modules:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: photobook
    values:
      layout: photobook
      gallery: true
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: notes
    values:
      layout: article

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed
